baseURL: https://bangtedy.github.io/wasagri/
languageCode: en-us
defaultContentLanguage: en
title: Cayman
theme: cayman-hugo-theme
googleAnalytics: UA-123456789-1
disqusShortname: yourdiscussshortname
pygmentsCodefences: yes
pygmentsStyle: pygments
taxonomies:
  tag: tags
permalinks:
  post: /:filename/
params:
  blockquote_text_color: '#819198'
  body_link_color: '#1e6bb8'
  body_text_color: '#606c71'
  border_color: '#dce6f0'
  code_background_color: '#f3f6fa'
  code_text_color: '#567482'
  dateFormat: '2006-01-02'
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme).
    Deployed to [Netlify](https://www.netlify.com/).
  header_background_color: '#159957'
  header_background_color_secondary: '#155799'
  header_heading_color: '#fff'
  hr_border_color: '#eff0f1'
  katex: yes
  large_breakpoint: 64em
  medium_breakpoint: 42em
  project_name: Wawasan Agribisnis
  project_tagline: Tedy Herlambang
  section_headings_color: '#159957'
  table_border_color: '#e9ebec'
menu:
  nav:
    - name: Deskripsi Mata Kuliah
      url: /pengantar/
      weight: 1
    #- name: Tags
    #  url: /tags/
    #  weight: 2
    - name: Materi
      url: /materi/
      weight: 3
    #- name: RSS
    #  url: /index.xml
    #  weight: 4
